"""strategies/roll_signals.py — Sprint 9.

Converts urgent RollDecision objects into executable TradeSignals so the
AutoTrader can close or roll positions automatically.

Generated signals have:
  - direction  = SHORT (sell-to-close a long put / long option)
  - confidence = 1.0   (roll is compulsory — no discretion)
  - notes      = "ROLL_CLOSE:<action>:<reason>"
                 (signals AutoTrader to bypass throttle/confidence filters)

Usage::

    from strategies.roll_signals import roll_decisions_to_signals

    urgent = roll_mgr.urgent_only(positions)
    signals = roll_decisions_to_signals(urgent, positions, account_value_usd=50_000)
    for sig in signals:
        print(sig.ticker, sig.direction, sig.notes)
"""
from __future__ import annotations

import os

import structlog

_log = structlog.get_logger(__name__)

# Notes prefix that AutoTrader uses to identify compulsory close signals.
ROLL_CLOSE_TAG = "ROLL_CLOSE"

# Actions that require an immediate order (vs. HOLD / NOT_OPTION / EXPIRED).
_ACTIONABLE_ACTIONS = {"roll", "close", "dead_put"}


def roll_decisions_to_signals(
    decisions: list,
    positions: list,
    account_value_usd: float = 0.0,
) -> list:
    """Convert a list of RollDecisions into executable TradeSignals.

    Only ROLL, CLOSE, and DEAD_PUT actions produce signals.
    HOLD, EXPIRED, and NOT_OPTION are skipped.

    Args:
        decisions:          List of ``RollDecision`` objects (from RollManager).
        positions:          List of ``PositionSnapshot`` objects — used to look
                            up the current market_value for position sizing.
        account_value_usd:  Account size.  0 → reads ``ACCOUNT_VALUE_USD`` env
                            var, falls back to 50 000.

    Returns:
        List of ``TradeSignal`` objects ready to pass to ``AutoTrader.run_once()``.
    """
    from shared.signal import Direction, TradeSignal  # noqa: PLC0415

    if account_value_usd <= 0:
        account_value_usd = float(os.getenv("ACCOUNT_VALUE_USD", "50000"))

    # Build a lookup so we can find each position's current market value.
    pos_by_symbol: dict = {getattr(p, "symbol", "").upper(): p for p in positions}

    signals: list = []

    for decision in decisions:
        action_val = decision.action.value if hasattr(decision.action, "value") else str(decision.action)
        if action_val not in _ACTIONABLE_ACTIONS:
            continue

        sym = decision.symbol.upper()
        pos = pos_by_symbol.get(sym)

        if pos is None:
            _log.warning(
                "roll_signal_no_position",
                symbol=sym,
                action=action_val,
            )
            continue

        # Size fraction = position's current market value as fraction of account.
        # Capped at 50% (pathological safety guard) and floored at 0.1%.
        market_value = abs(float(getattr(pos, "market_value", 0.0)))
        if account_value_usd > 0 and market_value > 0:
            size_fraction = min(market_value / account_value_usd, 0.50)
        else:
            size_fraction = 0.05   # fallback: 5% minimum close size
        size_fraction = max(size_fraction, 0.001)

        entry = float(getattr(pos, "market_price", 0.0))
        expiry = getattr(decision, "expiry", None)
        strike = getattr(decision, "strike", None)

        notes = f"{ROLL_CLOSE_TAG}:{action_val}:{decision.reason}"

        sig = TradeSignal(
            ticker=sym,
            direction=Direction.SHORT,   # sell-to-close
            confidence=1.0,              # compulsory — no confidence filter
            entry=entry,
            stop=0.0,
            target=0.0,
            size=size_fraction,
            strategy="roll_manager",
            expiry=expiry,
            strike=strike,
            notes=notes,
        )
        signals.append(sig)
        _log.info(
            "roll_signal_generated",
            symbol=sym,
            action=action_val,
            dte=getattr(decision, "dte", None),
            size=round(size_fraction, 4),
        )

    return signals


def is_roll_close_signal(signal) -> bool:
    """Return True if this signal was generated by the roll manager.

    AutoTrader uses this to bypass throttle and confidence filters for
    compulsory close orders.
    """
    return str(getattr(signal, "notes", "")).startswith(ROLL_CLOSE_TAG)
