"""strategies/stop_signals.py — Sprint 11.

Converts ``StopDecision`` objects (from ``StopManager``) into executable
``TradeSignal``s for ``AutoTrader.run_once()``.

Generated signals have:
  - direction  = SHORT (sell-to-close)
  - confidence = 1.0  (stop/TP is compulsory — no discretion)
  - notes      = "STOP_CLOSE:<trigger>:<reason>"
                 (``AutoTrader`` uses this to bypass throttle/confidence checks)

Usage::

    from strategies.stop_signals import stop_decisions_to_signals, is_stop_close_signal

    decisions = stop_mgr.scan(positions, account_value_usd=50_000)
    signals   = stop_decisions_to_signals(decisions, positions, account_value_usd=50_000)
    summary   = auto_trader.run_once(signals)
"""
from __future__ import annotations

import os

import structlog

_log = structlog.get_logger(__name__)

# Notes prefix that AutoTrader uses to identify compulsory stop/TP close signals.
STOP_CLOSE_TAG = "STOP_CLOSE"


def stop_decisions_to_signals(
    decisions: list,
    positions: list,
    account_value_usd: float = 0.0,
) -> list:
    """Convert ``StopDecision`` objects into executable ``TradeSignal``s.

    Args:
        decisions:          List of ``StopDecision`` objects (from StopManager).
        positions:          List of ``PositionSnapshot`` objects — used to look
                            up current market_price for the ``entry`` field.
        account_value_usd:  Account size in USD.  0 → reads ``ACCOUNT_VALUE_USD``
                            env var; falls back to 50 000.

    Returns:
        List of ``TradeSignal`` objects ready to pass to ``AutoTrader.run_once()``.
    """
    from shared.signal import Direction, TradeSignal  # noqa: PLC0415

    if account_value_usd <= 0:
        account_value_usd = float(os.getenv("ACCOUNT_VALUE_USD", "50000"))

    # Position lookup for market_price (best available entry estimate).
    pos_by_symbol: dict = {
        getattr(p, "symbol", "").upper(): p for p in positions
    }

    signals: list = []

    for decision in decisions:
        sym = decision.symbol.upper()
        pos = pos_by_symbol.get(sym)

        # Size fraction = current market_value / account.
        # Capped at 50% (safety guard); floor at 0.1%.
        mkt_val = decision.market_value
        if account_value_usd > 0 and mkt_val > 0:
            size_fraction = min(mkt_val / account_value_usd, 0.50)
        else:
            size_fraction = 0.05   # fallback minimum
        size_fraction = max(size_fraction, 0.001)

        entry = float(getattr(pos, "market_price", 0.0)) if pos else 0.0
        notes = f"{STOP_CLOSE_TAG}:{decision.trigger}:{decision.reason}"

        sig = TradeSignal(
            ticker=sym,
            direction=Direction.SHORT,   # sell-to-close
            confidence=1.0,              # compulsory — bypass confidence filter
            entry=entry,
            stop=0.0,
            target=0.0,
            size=size_fraction,
            strategy="stop_manager",
            notes=notes,
        )
        signals.append(sig)
        _log.info(
            "stop_signal_generated",
            symbol=sym,
            trigger=decision.trigger,
            pnl_pct=round(decision.pnl_pct * 100, 1),
            size=round(size_fraction, 4),
        )

    return signals


def is_stop_close_signal(signal) -> bool:
    """Return ``True`` if this signal was generated by the stop manager.

    AutoTrader uses this to bypass the throttle and confidence filters for
    compulsory stop-loss and take-profit close orders.
    """
    return str(getattr(signal, "notes", "")).startswith(STOP_CLOSE_TAG)
