from __future__ import annotations

"""Polymarket Council formatter — render insights as Markdown."""

from datetime import datetime, timezone

from councils.polymarket.models import CouncilEntry, MarketInsight, MarketSnapshot


def format_to_markdown(
    markets: list[MarketSnapshot],
    insights: MarketInsight,
) -> str:
    """Render a full Polymarket Council report as Markdown."""
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = []

    lines.append(f"# Polymarket Council Report — {ts}")
    lines.append("")
    lines.append(f"> {insights.summary}")
    lines.append("")

    # ── Volume leaders ──────────────────────────────────────────────────────
    lines.append("## Top Markets by Volume")
    lines.append("")
    lines.append("| Market | Volume | YES Price |")
    lines.append("|--------|-------:|----------:|")
    for m in insights.top_by_volume:
        lines.append(f"| {m['question'][:80]} | ${m['volume']:,.0f} | {m['yes']:.1%} |")
    lines.append("")

    # ── Liquidity leaders ───────────────────────────────────────────────────
    lines.append("## Top Markets by Liquidity")
    lines.append("")
    lines.append("| Market | Liquidity | YES Price |")
    lines.append("|--------|----------:|----------:|")
    for m in insights.top_by_liquidity:
        lines.append(f"| {m['question'][:80]} | ${m['liquidity']:,.0f} | {m['yes']:.1%} |")
    lines.append("")

    # ── Arbitrage opportunities ─────────────────────────────────────────────
    if insights.arb_opportunities:
        lines.append("## Arbitrage Opportunities")
        lines.append("")
        lines.append("| Market | YES | NO | Edge | Side |")
        lines.append("|--------|----:|---:|-----:|------|")
        for arb in insights.arb_opportunities[:15]:
            lines.append(
                f"| {arb.question[:70]} | {arb.yes_price:.3f} | {arb.no_price:.3f} "
                f"| {arb.edge_pct:.2f}% | {arb.side} |"
            )
        lines.append("")

    # ── High conviction ─────────────────────────────────────────────────────
    if insights.high_conviction:
        lines.append("## High Conviction Markets (>85% or <15%)")
        lines.append("")
        for hc in insights.high_conviction[:10]:
            lines.append(f"- **{hc['question'][:80]}** — YES {hc['yes']:.1%} (${hc['volume']:,.0f} vol)")
        lines.append("")

    # ── Toss-ups ────────────────────────────────────────────────────────────
    if insights.low_conviction:
        lines.append("## Toss-Up Markets (40-60%)")
        lines.append("")
        for lc in insights.low_conviction[:10]:
            lines.append(f"- **{lc['question'][:80]}** — YES {lc['yes']:.1%} (${lc['volume']:,.0f} vol)")
        lines.append("")

    # ── Category breakdown ──────────────────────────────────────────────────
    if insights.category_breakdown:
        lines.append("## Categories")
        lines.append("")
        for cat, count in sorted(insights.category_breakdown.items(), key=lambda x: x[1], reverse=True):
            lines.append(f"- **{cat}**: {count} markets")
        lines.append("")

    # ── All markets table ───────────────────────────────────────────────────
    lines.append("## All Scanned Markets")
    lines.append("")
    lines.append(f"Total: {len(markets)} markets, ${insights.total_volume:,.0f} total volume")
    lines.append("")
    lines.append("| # | Market | YES | NO | Volume | Liq |")
    lines.append("|--:|--------|----:|---:|-------:|----:|")
    sorted_markets = sorted(markets, key=lambda m: m.volume, reverse=True)
    for i, m in enumerate(sorted_markets[:50], 1):
        lines.append(
            f"| {i} | {m.question[:65]} | {m.yes_price:.3f} | {m.no_price:.3f} "
            f"| ${m.volume:,.0f} | ${m.liquidity:,.0f} |"
        )
    if len(markets) > 50:
        lines.append(f"| ... | *{len(markets) - 50} more markets omitted* | | | | |")
    lines.append("")

    lines.append(f"---\n*Generated by Polymarket Council at {ts}*\n")
    return "\n".join(lines)
