"""
Storm Lifeboat Executor — Commodity ETF + Moon Phase Bridge
=============================================================
Maps Storm Lifeboat SeeSawSignal objects → exchange orders via
StrategicDoctrineEngine terrain assessment and lunar timing gates.

The Storm Lifeboat produces SeeSawSignal and TrackedPosition objects
but has no execution path.  This module closes that gap:

    1. Reads current SeeSaw phase, signals, and tracked positions
    2. Checks lunar timing window (golden-ratio offsets within 28-day moons)
    3. Calls StrategicDoctrineEngine.assess_terrain() for go/no-go
    4. Generates ETF/commodity orders routed via IBKR or Moomoo
    5. Manages entry/exit with stop-loss from TrackedPosition

Usage:
    executor = LifeboatExecutor()
    await executor.connect()
    orders = executor.generate_orders(cycle_report, market_snapshot)
    if not executor.dry_run:
        results = await executor.execute(orders)
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# ── Storm Lifeboat imports ──────────────────────────────────────────────
try:
    from strategies.storm_lifeboat.capital_engine import (
        ASSET_TO_ETF,
        SeeSawPhase,
        SeeSawSignal,
        TrackedPosition,
    )
    LIFEBOAT_AVAILABLE = True
except ImportError:
    LIFEBOAT_AVAILABLE = False
    ASSET_TO_ETF = {}

# ── Lunar timing ───────────────────────────────────────────────────────
try:
    from strategies.storm_lifeboat.lunar_phi import get_current_moon_window
    LUNAR_AVAILABLE = True
except ImportError:
    LUNAR_AVAILABLE = False

# ── Doctrine ───────────────────────────────────────────────────────────
try:
    from aac.doctrine.strategic_doctrine import get_strategic_doctrine_engine
    DOCTRINE_AVAILABLE = True
except ImportError:
    DOCTRINE_AVAILABLE = False

# ── Exchange connectors ────────────────────────────────────────────────
try:
    from TradingExecution.exchange_connectors.ibkr_connector import IBKRConnector
    IBKR_AVAILABLE = True
except ImportError:
    IBKR_AVAILABLE = False

try:
    from TradingExecution.exchange_connectors.moomoo_connector import MoomooConnector
    MOOMOO_AVAILABLE = True
except ImportError:
    MOOMOO_AVAILABLE = False


# ── Order spec ──────────────────────────────────────────────────────────

class LifeboatAction(str, Enum):
    OPEN_LONG = "open_long"
    CLOSE_LONG = "close_long"
    OPEN_SHORT = "open_short"
    CLOSE_SHORT = "close_short"


@dataclass
class LifeboatOrderSpec:
    """A single order generated by the Lifeboat executor."""
    etf: str
    action: LifeboatAction
    quantity_usd: float       # Dollar amount (notional)
    shares: int = 0           # Computed from price
    limit_price: Optional[float] = None
    phase: str = ""
    moon_window: str = ""
    confidence: float = 0.0
    rationale: str = ""
    doctrine_posture: str = ""
    terrain_confidence: float = 0.0
    stop_loss_pct: float = 0.08
    trailing_stop_pct: float = 0.05


# ── Executor ────────────────────────────────────────────────────────────

class LifeboatExecutor:
    """
    Bridge between Storm Lifeboat see-saw engine and exchange execution.

    Checks doctrine terrain and lunar timing before generating orders.
    Supports IBKR (primary) and Moomoo (fallback) connectors.
    """

    def __init__(
        self,
        connector_type: str = "ibkr",
        host: str = "",
        port: int = 7496,
        client_id: int = 11,
        account: str = "",
        dry_run: bool = True,
        position_size_usd: float = 500.0,
        max_total_exposure: float = 5000.0,
        require_lunar_window: bool = True,
    ):
        self.dry_run = dry_run
        self.connector_type = connector_type
        self.position_size_usd = position_size_usd
        self.max_total_exposure = max_total_exposure
        self.require_lunar_window = require_lunar_window
        self._connected = False
        self._connector: Optional[Any] = None

        if not dry_run:
            if connector_type == "ibkr" and IBKR_AVAILABLE:
                self._connector = IBKRConnector(
                    host=host, port=port, client_id=client_id,
                    account=account, paper=(port == 7497),
                )
            elif connector_type == "moomoo" and MOOMOO_AVAILABLE:
                self._connector = MoomooConnector()

    # ── Connection ──────────────────────────────────────────────────────

    async def connect(self) -> bool:
        if self._connector is None:
            logger.info("LifeboatExecutor: dry-run mode, no exchange connection needed")
            return True
        self._connected = await self._connector.connect()
        return self._connected

    async def disconnect(self) -> None:
        if self._connector and self._connected:
            await self._connector.disconnect()
            self._connected = False

    # ── Lunar timing gate ───────────────────────────────────────────────

    def check_lunar_window(self) -> Dict[str, Any]:
        """
        Check if we are inside a golden-ratio action window.

        Returns dict with in_window (bool), moon_name, window_name.
        If lunar module is unavailable, returns permissive default.
        """
        if not LUNAR_AVAILABLE:
            return {"in_window": True, "moon_name": "unknown", "window_name": "n/a"}
        try:
            window = get_current_moon_window()
            return {
                "in_window": window.get("active", True),
                "moon_name": window.get("moon_name", "?"),
                "window_name": window.get("window_name", "?"),
            }
        except Exception as e:
            logger.warning("Lunar window check failed: %s", e)
            return {"in_window": True, "moon_name": "error", "window_name": str(e)}

    # ── Doctrine terrain check ──────────────────────────────────────────

    def check_terrain(self, market_snapshot: Dict[str, Any]) -> Dict[str, Any]:
        """
        Call StrategicDoctrineEngine.assess_terrain() with market data.
        Same pattern as WarRoomExecutor for consistency.
        """
        if not DOCTRINE_AVAILABLE:
            return {"posture": "unknown", "confidence": 0.5, "go": True, "reason": "doctrine unavailable"}

        engine = get_strategic_doctrine_engine()
        try:
            terrain = engine.assess_terrain(
                volatility=market_snapshot.get("volatility", 0.5),
                liquidity=market_snapshot.get("liquidity", 0.5),
                trend=market_snapshot.get("trend", 0.5),
                sr_proximity=market_snapshot.get("sr_proximity", 0.5),
                session_quality=market_snapshot.get("session_quality", 0.5),
            )
            posture = getattr(terrain, "posture", "unknown")
            confidence = getattr(terrain, "confidence", 0.5)
            go = (str(posture).lower() not in ("retreat", "desperate")) and confidence >= 0.3
            return {
                "posture": str(posture),
                "confidence": confidence,
                "go": go,
                "reason": f"terrain={getattr(terrain, 'terrain_type', '?')}, posture={posture}",
            }
        except Exception as e:
            logger.warning("Doctrine terrain check failed: %s", e)
            return {"posture": "unknown", "confidence": 0.5, "go": True, "reason": str(e)}

    # ── Order generation ────────────────────────────────────────────────

    def generate_orders(
        self,
        signals: List[Any],
        market_snapshot: Dict[str, Any],
        tracked_positions: Optional[List[Any]] = None,
    ) -> List[LifeboatOrderSpec]:
        """
        Generate orders from SeeSawSignal list, filtered by doctrine + lunar timing.

        Args:
            signals: List of SeeSawSignal from capital_engine cycle
            market_snapshot: Market data for doctrine assessment
            tracked_positions: Current TrackedPosition list for exit checks

        Returns:
            List of LifeboatOrderSpec ready for execution or logging.
        """
        if not LIFEBOAT_AVAILABLE:
            logger.error("Storm Lifeboat not available — cannot generate orders")
            return []

        # 1. Doctrine terrain gate
        terrain = self.check_terrain(market_snapshot)
        if not terrain["go"]:
            logger.warning("Doctrine terrain BLOCKED: %s", terrain["reason"])
            return []

        # 2. Lunar timing gate
        lunar = self.check_lunar_window()
        if self.require_lunar_window and not lunar["in_window"]:
            logger.info(
                "Lunar window closed (moon=%s) — deferring orders",
                lunar["moon_name"],
            )
            return []

        orders: List[LifeboatOrderSpec] = []

        # 3. Process exit signals from tracked positions (stop-loss)
        if tracked_positions:
            for pos in tracked_positions:
                if hasattr(pos, "stopped_out") and pos.stopped_out:
                    orders.append(LifeboatOrderSpec(
                        etf=pos.etf,
                        action=LifeboatAction.CLOSE_LONG,
                        quantity_usd=pos.quantity,
                        rationale=f"STOP: {pos.stop_trigger}",
                        phase="exit",
                        moon_window=lunar["moon_name"],
                        doctrine_posture=terrain["posture"],
                        terrain_confidence=terrain["confidence"],
                    ))

        # 4. Process new entry signals
        total_exposure = sum(o.quantity_usd for o in orders if o.action == LifeboatAction.OPEN_LONG)
        existing_etfs = set()
        if tracked_positions:
            existing_etfs = {p.etf for p in tracked_positions if not getattr(p, "stopped_out", False)}

        for sig in signals:
            if not hasattr(sig, "etf") or not hasattr(sig, "direction"):
                continue

            etf = sig.etf
            direction = sig.direction.upper() if isinstance(sig.direction, str) else str(sig.direction)
            confidence = getattr(sig, "confidence", 0.5)

            if direction == "CLOSE" and etf in existing_etfs:
                orders.append(LifeboatOrderSpec(
                    etf=etf,
                    action=LifeboatAction.CLOSE_LONG,
                    quantity_usd=self.position_size_usd,
                    confidence=confidence,
                    rationale=getattr(sig, "reason", "close signal"),
                    phase=getattr(sig, "off_ramp", ""),
                    moon_window=lunar["moon_name"],
                    doctrine_posture=terrain["posture"],
                    terrain_confidence=terrain["confidence"],
                ))
            elif direction == "LONG" and etf not in existing_etfs:
                if total_exposure + self.position_size_usd > self.max_total_exposure:
                    logger.info("Exposure cap reached — skipping %s", etf)
                    continue
                # Scale size by confidence and terrain confidence
                scaled_size = self.position_size_usd * confidence * terrain["confidence"]
                scaled_size = max(100.0, min(scaled_size, self.position_size_usd))
                orders.append(LifeboatOrderSpec(
                    etf=etf,
                    action=LifeboatAction.OPEN_LONG,
                    quantity_usd=scaled_size,
                    confidence=confidence,
                    rationale=getattr(sig, "reason", ""),
                    phase=getattr(sig, "off_ramp", ""),
                    moon_window=lunar["moon_name"],
                    doctrine_posture=terrain["posture"],
                    terrain_confidence=terrain["confidence"],
                    stop_loss_pct=0.08,
                    trailing_stop_pct=0.05,
                ))
                total_exposure += scaled_size

        logger.info(
            "LifeboatExecutor: generated %d orders (moon=%s, posture=%s, conf=%.2f)",
            len(orders), lunar["moon_name"], terrain["posture"], terrain["confidence"],
        )
        return orders

    # ── Execution ───────────────────────────────────────────────────────

    async def execute(self, orders: List[LifeboatOrderSpec]) -> List[Dict[str, Any]]:
        """
        Execute Lifeboat orders through IBKR/Moomoo connector.

        In dry-run mode, logs orders without sending to exchange.
        """
        results: List[Dict[str, Any]] = []
        for order in orders:
            if self.dry_run:
                logger.info(
                    "DRY-RUN: %s %s $%.0f [moon=%s, posture=%s] %s",
                    order.action.value, order.etf, order.quantity_usd,
                    order.moon_window, order.doctrine_posture, order.rationale,
                )
                results.append({"order": order, "status": "dry_run", "success": True})
                continue

            if not self._connector or not self._connected:
                results.append({"order": order, "status": "not_connected", "success": False})
                continue

            try:
                side = "buy" if order.action in (LifeboatAction.OPEN_LONG, LifeboatAction.CLOSE_SHORT) else "sell"
                exchange_order = await self._connector.place_order(
                    symbol=order.etf,
                    side=side,
                    order_type="limit" if order.limit_price else "market",
                    quantity=order.shares or int(order.quantity_usd / (order.limit_price or 100)),
                    price=order.limit_price,
                )
                results.append({
                    "order": order,
                    "exchange_order": exchange_order,
                    "status": "submitted",
                    "success": True,
                })
                logger.info("SUBMITTED: %s %s → order_id=%s", order.etf, side,
                            getattr(exchange_order, "order_id", "?"))
            except Exception as e:
                logger.error("FAILED: %s %s — %s", order.etf, order.action.value, e)
                results.append({"order": order, "status": "error", "success": False, "error": str(e)})

        return results

    # ── Summary ─────────────────────────────────────────────────────────

    def get_summary(self) -> Dict[str, Any]:
        return {
            "executor": "LifeboatExecutor",
            "dry_run": self.dry_run,
            "connector_type": self.connector_type,
            "connected": self._connected,
            "ibkr_available": IBKR_AVAILABLE,
            "moomoo_available": MOOMOO_AVAILABLE,
            "lifeboat_available": LIFEBOAT_AVAILABLE,
            "lunar_available": LUNAR_AVAILABLE,
            "doctrine_available": DOCTRINE_AVAILABLE,
            "position_size_usd": self.position_size_usd,
            "max_total_exposure": self.max_total_exposure,
            "require_lunar_window": self.require_lunar_window,
        }


# ── Singleton ───────────────────────────────────────────────────────────

_executor: Optional[LifeboatExecutor] = None


def get_lifeboat_executor(**kwargs: Any) -> LifeboatExecutor:
    global _executor
    if _executor is None:
        _executor = LifeboatExecutor(**kwargs)
    return _executor
