"""
PolyMC Monitor — Hourly Monitoring Loop with Exit Strategy Engine
==================================================================
AAC Polymarket Division

Monitors all portfolio positions hourly:
  - Refreshes live prices from CLOB/Gamma API
  - Checks per-bet exit signals (take-profit / stop-loss)
  - Checks portfolio-level exit rules (EV floor, partial profit)
  - Logs all signals and state transitions
  - Can auto-execute exits via CLOB SDK (sell limit orders)

Exit Strategy Rules:
  Per-Bet:
    - Take Profit: price >= bet.take_profit --> SELL
    - Stop Loss:   price <= bet.stop_loss   --> SELL
    - Partial Profit: price >= entry * 1.5  --> SELL 50%

  Portfolio-Level:
    - EV Floor: portfolio EV < 4% --> exit all positions
    - Concentration: single bet > 40% of portfolio value --> rebalance alert

Usage:
    python -m strategies.polymarket_division.polymc_monitor             # one check
    python -m strategies.polymarket_division.polymc_monitor --loop      # hourly loop
    python -m strategies.polymarket_division.polymc_monitor --json      # JSON output
    python -m strategies.polymarket_division.polymc_monitor --execute   # auto-execute exits
"""
from __future__ import annotations

import argparse
import asyncio
import io
import json
import logging
import os
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

if hasattr(sys.stdout, "buffer") and sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")

try:
    import aiohttp
except ImportError:
    aiohttp = None  # type: ignore[assignment]

from strategies.polymarket_division.polymc_agent import (
    CLOB_API,
    GAMMA_API,
    PARTIAL_PROFIT_THRESHOLD,
    PORTFOLIO_EV_FLOOR,
    TARGET_PORTFOLIO,
    PolyMCAgent,
    TargetBet,
)

logger = logging.getLogger(__name__)

# ============================================================================
# EXIT SIGNAL TYPES
# ============================================================================

@dataclass
class ExitSignal:
    """An exit signal generated by the monitor."""
    bet_name: str
    signal_type: str  # "take_profit" | "stop_loss" | "partial_profit" | "ev_floor" | "concentration"
    current_price: float
    threshold: float
    action: str  # "SELL_ALL" | "SELL_50%" | "ALERT"
    urgency: str  # "immediate" | "next_check" | "info"
    timestamp: datetime = field(default_factory=datetime.now)
    executed: bool = False

    def __str__(self) -> str:
        return (
            f"[{self.signal_type.upper()}] {self.bet_name}: "
            f"price=${self.current_price:.3f} vs threshold=${self.threshold:.3f} "
            f"-> {self.action} ({self.urgency})"
        )


# ============================================================================
# MONITOR ENGINE
# ============================================================================

class PolyMCMonitor:
    """
    Hourly monitor for PolyMC portfolio positions.
    Refreshes prices, checks exit rules, and generates signals.
    """

    def __init__(self, agent: Optional[PolyMCAgent] = None):
        self.agent = agent or PolyMCAgent()
        self.portfolio = self.agent.portfolio
        self.signals: List[ExitSignal] = []
        self.check_count = 0
        self._session: Optional[Any] = None

    async def _get_session(self):
        if aiohttp is None:
            raise ImportError("aiohttp required: pip install aiohttp")
        if self._session is None or self._session.closed:
            self._session = aiohttp.ClientSession()
        return self._session

    async def close(self):
        if self._session and not self._session.closed:
            await self._session.close()
        await self.agent.close()

    # ─── Price Refresh ────────────────────────────────────────────────

    async def refresh_prices(self):
        """Fetch current prices for all portfolio bets from Gamma API."""
        session = await self._get_session()

        for bet in self.portfolio:
            if not bet.market_slug and not bet.condition_id:
                continue

            try:
                # Try by slug first, then condition_id
                if bet.market_slug:
                    url = f"{GAMMA_API}/markets?slug={bet.market_slug}&limit=1"
                else:
                    url = f"{GAMMA_API}/markets?condition_id={bet.condition_id}&limit=1"

                async with session.get(url, timeout=aiohttp.ClientTimeout(total=10)) as resp:
                    if resp.status != 200:
                        continue
                    data = await resp.json()

                if data:
                    m = data[0]
                    raw_prices = m.get("outcomePrices", "")
                    if isinstance(raw_prices, str) and raw_prices:
                        cleaned = raw_prices.strip().strip("[]")
                        parts = [p.strip().strip('"') for p in cleaned.split(",")]
                        if parts:
                            try:
                                yes_p = float(parts[0])
                                prev = bet.current_price
                                bet.current_price = yes_p if bet.side == "YES" else (1.0 - yes_p)

                                # Update PnL
                                if bet.fill_price > 0:
                                    shares = bet.bet_size / bet.fill_price
                                    bet.pnl = (bet.current_price - bet.fill_price) * shares
                                elif bet.entry_price > 0:
                                    shares = bet.bet_size / bet.entry_price
                                    bet.pnl = (bet.current_price - bet.entry_price) * shares

                                if prev != bet.current_price:
                                    logger.debug(
                                        f"{bet.name}: ${prev:.3f} -> ${bet.current_price:.3f}"
                                    )
                            except ValueError:
                                pass

                    # Also update token_id if missing
                    if not bet.token_id:
                        tokens = m.get("clobTokenIds", "")
                        if isinstance(tokens, str) and tokens:
                            try:
                                parsed = json.loads(tokens)
                                if isinstance(parsed, list) and len(parsed) >= 2:
                                    bet.token_id = str(parsed[0]) if bet.side == "YES" else str(parsed[1])
                            except (json.JSONDecodeError, TypeError):
                                pass

            except Exception as e:
                logger.warning(f"Price refresh failed for {bet.name}: {e}")

            await asyncio.sleep(0.15)

    # ─── Exit Strategy Checks ────────────────────────────────────────

    def check_exit_signals(self) -> List[ExitSignal]:
        """Check all exit rules and generate signals."""
        signals: List[ExitSignal] = []

        for bet in self.portfolio:
            if bet.status not in ("pending", "active"):
                continue
            if bet.current_price <= 0:
                continue

            # Take Profit
            if bet.current_price >= bet.take_profit:
                signals.append(ExitSignal(
                    bet_name=bet.name,
                    signal_type="take_profit",
                    current_price=bet.current_price,
                    threshold=bet.take_profit,
                    action="SELL_ALL",
                    urgency="immediate",
                ))

            # Stop Loss
            if bet.current_price <= bet.stop_loss:
                signals.append(ExitSignal(
                    bet_name=bet.name,
                    signal_type="stop_loss",
                    current_price=bet.current_price,
                    threshold=bet.stop_loss,
                    action="SELL_ALL",
                    urgency="immediate",
                ))

            # Partial Profit (+50% from entry)
            ref_price = bet.fill_price if bet.fill_price > 0 else bet.entry_price
            if ref_price > 0 and bet.current_price >= ref_price * PARTIAL_PROFIT_THRESHOLD:
                signals.append(ExitSignal(
                    bet_name=bet.name,
                    signal_type="partial_profit",
                    current_price=bet.current_price,
                    threshold=ref_price * PARTIAL_PROFIT_THRESHOLD,
                    action="SELL_50%",
                    urgency="next_check",
                ))

        # Portfolio-level EV check
        total_cost = sum(b.bet_size for b in self.portfolio if b.status in ("pending", "active"))
        total_ev = sum(b.ev for b in self.portfolio if b.status in ("pending", "active"))
        if total_cost > 0:
            portfolio_ev_pct = total_ev / total_cost
            if portfolio_ev_pct < PORTFOLIO_EV_FLOOR:
                signals.append(ExitSignal(
                    bet_name="PORTFOLIO",
                    signal_type="ev_floor",
                    current_price=portfolio_ev_pct,
                    threshold=PORTFOLIO_EV_FLOOR,
                    action="SELL_ALL",
                    urgency="immediate",
                ))

        # Concentration check
        active_bets = [b for b in self.portfolio if b.status in ("pending", "active") and b.current_price > 0]
        if active_bets:
            total_value = sum(
                (b.bet_size / max(b.entry_price, 0.001)) * b.current_price
                for b in active_bets
            )
            for bet in active_bets:
                bet_value = (bet.bet_size / max(bet.entry_price, 0.001)) * bet.current_price
                if total_value > 0 and bet_value / total_value > 0.40:
                    signals.append(ExitSignal(
                        bet_name=bet.name,
                        signal_type="concentration",
                        current_price=bet_value / total_value,
                        threshold=0.40,
                        action="ALERT",
                        urgency="info",
                    ))

        self.signals.extend(signals)
        return signals

    # ─── Single Check Cycle ───────────────────────────────────────────

    async def run_check(self) -> Dict[str, Any]:
        """Run one monitoring check: refresh prices, check exits, report."""
        self.check_count += 1
        check_time = datetime.now()

        # Refresh prices
        await self.refresh_prices()

        # Check exit signals
        signals = self.check_exit_signals()

        # Build status
        immediate = [s for s in signals if s.urgency == "immediate"]
        alerts = [s for s in signals if s.urgency != "immediate"]

        result = {
            "check_number": self.check_count,
            "timestamp": check_time.isoformat(),
            "signals": len(signals),
            "immediate_exits": len(immediate),
            "alerts": len(alerts),
            "portfolio": [],
        }

        for bet in self.portfolio:
            result["portfolio"].append({
                "name": bet.name,
                "side": bet.side,
                "entry": bet.entry_price,
                "current": bet.current_price,
                "tp": bet.take_profit,
                "sl": bet.stop_loss,
                "pnl": round(bet.pnl, 2),
                "status": bet.status,
            })

        return result

    # ─── Report ───────────────────────────────────────────────────────

    def generate_check_report(self, result: Dict[str, Any]) -> str:
        """Format a monitoring check result as a report."""
        lines = []
        lines.append("")
        lines.append("=" * 100)
        lines.append(f"  POLYMC MONITOR -- Check #{result['check_number']} at {result['timestamp']}")
        lines.append(f"  Signals: {result['signals']} | "
                      f"Immediate Exits: {result['immediate_exits']} | "
                      f"Alerts: {result['alerts']}")
        lines.append("=" * 100)
        lines.append("")
        lines.append(f"  {'Market':<45} {'Side':>5} {'Entry':>7} {'Current':>8} "
                      f"{'TP':>7} {'SL':>7} {'PnL':>8} {'Status':>10}")
        lines.append("  " + "-" * 96)

        for p in result["portfolio"]:
            name = p["name"][:43] if len(p["name"]) > 43 else p["name"]
            # Color indicator
            if p["current"] >= p["tp"]:
                indicator = " TP!"
            elif p["current"] <= p["sl"]:
                indicator = " SL!"
            else:
                indicator = ""
            lines.append(
                f"  {name:<45} {p['side']:>5} ${p['entry']:.3f} "
                f"${p['current']:.3f} ${p['tp']:.2f} ${p['sl']:.2f} "
                f"${p['pnl']:>+7.2f} {p['status']:>10}{indicator}"
            )

        # Show signals
        recent = self.signals[-10:] if self.signals else []
        if recent:
            lines.append("")
            lines.append("  Recent Signals:")
            for s in recent:
                lines.append(f"    {s}")

        lines.append("")
        return "\n".join(lines)

    # ─── Continuous Loop ──────────────────────────────────────────────

    async def run_loop(self, interval_seconds: int = 3600, max_checks: int = 0):
        """
        Run continuous monitoring loop.
        Default: check every hour (3600s). Set max_checks=0 for infinite.
        """
        print(f"\n  PolyMC Monitor starting -- interval {interval_seconds}s")
        print(f"  Monitoring {len(self.portfolio)} positions")
        print(f"  Exit rules: per-bet TP/SL + portfolio EV floor {PORTFOLIO_EV_FLOOR:.0%}")
        print()

        checks = 0
        try:
            while True:
                result = await self.run_check()
                report = self.generate_check_report(result)
                print(report)

                # Log to file
                log_file = os.path.join(
                    os.path.dirname(__file__), "..", "..",
                    "logs", f"polymc_monitor_{datetime.now():%Y%m%d}.jsonl"
                )
                os.makedirs(os.path.dirname(log_file), exist_ok=True)
                with open(log_file, "a") as f:
                    f.write(json.dumps(result, default=str) + "\n")

                checks += 1
                if max_checks > 0 and checks >= max_checks:
                    break

                # Wait for next check
                print(f"  Next check in {interval_seconds}s...")
                await asyncio.sleep(interval_seconds)

        except KeyboardInterrupt:
            print("\n  Monitor stopped by user")
        finally:
            await self.close()


# ============================================================================
# CLI
# ============================================================================

async def _main():
    parser = argparse.ArgumentParser(description="PolyMC Monitor -- Hourly Exit Strategy Engine")
    parser.add_argument("--loop", action="store_true", help="Run continuous hourly monitoring")
    parser.add_argument("--interval", type=int, default=3600, help="Check interval in seconds")
    parser.add_argument("--checks", type=int, default=0, help="Max checks (0=infinite)")
    parser.add_argument("--json", action="store_true", help="JSON output")
    args = parser.parse_args()

    monitor = PolyMCMonitor()

    try:
        if args.loop:
            await monitor.run_loop(
                interval_seconds=args.interval,
                max_checks=args.checks,
            )
        else:
            result = await monitor.run_check()
            if args.json:
                print(json.dumps(result, indent=2, default=str))
            else:
                print(monitor.generate_check_report(result))
    finally:
        await monitor.close()


if __name__ == "__main__":
    sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", ".."))
    asyncio.run(_main())
