"""
War Room Executor — 5-Arm IBKR Options Bridge
===============================================
Maps War Room arm signals → IBKR option/equity orders via
StrategicDoctrineEngine terrain assessment.

The War Room produces Position objects and ArmAllocation rules
but has no execution path.  This module closes that gap:

    1. Reads current arm allocations + positions from war_room_engine
    2. Calls StrategicDoctrineEngine.assess_terrain() for go/no-go
    3. Generates ExchangeOrder-compatible order specs
    4. Routes through IBKRConnector (or dry-run logs)

Usage:
    executor = WarRoomExecutor()
    await executor.connect()
    orders = executor.generate_orders(market_snapshot, phase="accumulation")
    if not executor.dry_run:
        results = await executor.execute(orders)
"""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# ── War Room imports ────────────────────────────────────────────────────
try:
    from strategies.war_room_engine import (
        CURRENT_POSITIONS,
        ArmAllocation,
        ArmType,
        Position,
        get_arm_allocations,
    )
    WAR_ROOM_AVAILABLE = True
except ImportError:
    WAR_ROOM_AVAILABLE = False

# ── Doctrine import ────────────────────────────────────────────────────
try:
    from aac.doctrine.strategic_doctrine import get_strategic_doctrine_engine
    DOCTRINE_AVAILABLE = True
except ImportError:
    DOCTRINE_AVAILABLE = False

# ── IBKR connector ─────────────────────────────────────────────────────
try:
    from TradingExecution.exchange_connectors.base_connector import ExchangeOrder
    from TradingExecution.exchange_connectors.ibkr_connector import IBKRConnector
    IBKR_AVAILABLE = True
except ImportError:
    IBKR_AVAILABLE = False


# ── Order spec ──────────────────────────────────────────────────────────

class OrderAction(str, Enum):
    BUY = "buy"
    SELL = "sell"


@dataclass
class WarRoomOrderSpec:
    """A single order generated by the War Room executor."""
    arm: str
    symbol: str
    action: OrderAction
    order_type: str           # "option_put", "option_call", "equity_long", "equity_short"
    quantity: int
    limit_price: Optional[float] = None
    strike: Optional[float] = None
    expiry: Optional[str] = None
    rationale: str = ""
    doctrine_posture: str = ""
    terrain_confidence: float = 0.0

    @property
    def is_option(self) -> bool:
        return self.order_type.startswith("option_")


# ── Executor ────────────────────────────────────────────────────────────

class WarRoomExecutor:
    """
    Bridge between War Room 5-arm position system and IBKR execution.

    Checks doctrine terrain before generating orders. Generates order specs
    that can be executed via IBKRConnector or logged in dry-run mode.
    """

    def __init__(
        self,
        host: str = "",
        port: int = 7496,
        client_id: int = 10,
        account: str = "",
        dry_run: bool = True,
        max_premium_per_order: float = 500.0,
        max_total_premium: float = 2000.0,
    ):
        self.dry_run = dry_run
        self.max_premium_per_order = max_premium_per_order
        self.max_total_premium = max_total_premium
        self._connected = False
        self._connector: Optional[Any] = None

        if IBKR_AVAILABLE and not dry_run:
            self._connector = IBKRConnector(
                host=host,
                port=port,
                client_id=client_id,
                account=account,
                paper=(port == 7497),
            )

    # ── Connection ──────────────────────────────────────────────────────

    async def connect(self) -> bool:
        if self._connector is None:
            logger.info("WarRoomExecutor: dry-run mode, no IBKR connection needed")
            return True
        self._connected = await self._connector.connect()
        return self._connected

    async def disconnect(self) -> None:
        if self._connector and self._connected:
            await self._connector.disconnect()
            self._connected = False

    # ── Doctrine terrain check ──────────────────────────────────────────

    def check_terrain(self, market_snapshot: Dict[str, Any]) -> Dict[str, Any]:
        """
        Call StrategicDoctrineEngine.assess_terrain() with market data.

        Returns dict with posture, confidence, and go/no-go flag.
        If doctrine is unavailable, returns a permissive default.
        """
        if not DOCTRINE_AVAILABLE:
            return {"posture": "unknown", "confidence": 0.5, "go": True, "reason": "doctrine unavailable"}

        engine = get_strategic_doctrine_engine()
        try:
            terrain = engine.assess_terrain(
                volatility=market_snapshot.get("volatility", 0.5),
                liquidity=market_snapshot.get("liquidity", 0.5),
                trend=market_snapshot.get("trend", 0.5),
                sr_proximity=market_snapshot.get("sr_proximity", 0.5),
                session_quality=market_snapshot.get("session_quality", 0.5),
            )
            posture = getattr(terrain, "posture", "unknown")
            confidence = getattr(terrain, "confidence", 0.5)
            # Block trading if doctrine says "retreat" or confidence is very low
            go = (str(posture).lower() not in ("retreat", "desperate")) and confidence >= 0.3
            return {
                "posture": str(posture),
                "confidence": confidence,
                "go": go,
                "reason": f"terrain={getattr(terrain, 'terrain_type', '?')}, posture={posture}",
            }
        except Exception as e:
            logger.warning("Doctrine terrain check failed: %s", e)
            return {"posture": "unknown", "confidence": 0.5, "go": True, "reason": str(e)}

    # ── Order generation ────────────────────────────────────────────────

    def generate_orders(
        self,
        market_snapshot: Dict[str, Any],
        phase: str = "accumulation",
        existing_positions: Optional[List[Any]] = None,
    ) -> List[WarRoomOrderSpec]:
        """
        Generate order specs from arm allocations filtered by doctrine terrain.

        Args:
            market_snapshot: Dict with keys like vix, oil_price, gold_price, etc.
            phase: War room phase (accumulation / growth / rotation)
            existing_positions: Current positions to check against allocations

        Returns:
            List of WarRoomOrderSpec ready for execution or logging.
        """
        if not WAR_ROOM_AVAILABLE:
            logger.error("War Room Engine not available — cannot generate orders")
            return []

        # 1. Doctrine terrain gate
        terrain = self.check_terrain(market_snapshot)
        if not terrain["go"]:
            logger.warning(
                "Doctrine terrain BLOCKED order generation: %s", terrain["reason"]
            )
            return []

        # 2. Get arm allocations for phase
        allocations = get_arm_allocations(phase)
        positions = existing_positions or CURRENT_POSITIONS

        # 3. Build symbol set of existing positions per arm
        existing_by_arm: Dict[str, List[str]] = {}
        for pos in positions:
            arm_key = pos.arm.value if hasattr(pos.arm, "value") else str(pos.arm)
            existing_by_arm.setdefault(arm_key, []).append(pos.symbol)

        # 4. Generate orders for under-allocated arms
        orders: List[WarRoomOrderSpec] = []
        vix = market_snapshot.get("vix", 20.0)

        for alloc in allocations:
            arm_key = alloc.arm.value
            current_symbols = existing_by_arm.get(arm_key, [])

            # Skip arms that are already at or over target instrument count
            if len(current_symbols) >= len(alloc.instruments):
                continue

            for instrument_desc in alloc.instruments:
                # Parse instrument description into tradeable spec
                spec = self._parse_instrument(instrument_desc, alloc, terrain, vix)
                if spec and spec.symbol not in current_symbols:
                    orders.append(spec)

        # 5. Cap total notional premium
        total_premium = 0.0
        capped: List[WarRoomOrderSpec] = []
        for o in orders:
            premium = (o.limit_price or 1.0) * o.quantity * (100 if o.is_option else 1)
            if total_premium + premium <= self.max_total_premium:
                total_premium += premium
                capped.append(o)
            else:
                logger.info("Premium cap reached — skipping %s", o.symbol)

        logger.info(
            "WarRoomExecutor: generated %d orders (phase=%s, posture=%s, confidence=%.2f)",
            len(capped), phase, terrain["posture"], terrain["confidence"],
        )
        return capped

    def _parse_instrument(
        self,
        desc: str,
        alloc: ArmAllocation,
        terrain: Dict[str, Any],
        vix: float,
    ) -> Optional[WarRoomOrderSpec]:
        """Parse an instrument description string into an order spec."""
        desc_lower = desc.lower()

        # Extract symbol — first word that looks like a ticker
        parts = desc.split()
        symbol = parts[0].upper() if parts else ""
        if not symbol or len(symbol) > 5:
            return None

        # Determine order type
        if "put" in desc_lower:
            order_type = "option_put"
            action = OrderAction.BUY
        elif "call" in desc_lower:
            order_type = "option_call"
            action = OrderAction.BUY
        elif "short" in desc_lower:
            order_type = "equity_short"
            action = OrderAction.SELL
        else:
            order_type = "equity_long"
            action = OrderAction.BUY

        # Size: 1 contract for options, small position for equity
        quantity = 1
        limit_price = min(2.0 if vix > 25 else 1.0, self.max_premium_per_order / 100)

        return WarRoomOrderSpec(
            arm=alloc.arm.value,
            symbol=symbol,
            action=action,
            order_type=order_type,
            quantity=quantity,
            limit_price=limit_price if order_type.startswith("option_") else None,
            rationale=f"{alloc.entry_conditions} | {desc}",
            doctrine_posture=terrain["posture"],
            terrain_confidence=terrain["confidence"],
        )

    # ── Execution ───────────────────────────────────────────────────────

    async def execute(self, orders: List[WarRoomOrderSpec]) -> List[Dict[str, Any]]:
        """
        Execute order specs through IBKR connector.

        In dry-run mode, logs orders without sending to exchange.
        """
        results: List[Dict[str, Any]] = []
        for order in orders:
            if self.dry_run:
                logger.info(
                    "DRY-RUN: %s %s %s x%d @ %s [%s] (posture=%s)",
                    order.action.value, order.order_type, order.symbol,
                    order.quantity, order.limit_price, order.arm,
                    order.doctrine_posture,
                )
                results.append({"order": order, "status": "dry_run", "success": True})
                continue

            if not self._connector or not self._connected:
                results.append({"order": order, "status": "not_connected", "success": False})
                continue

            try:
                exchange_order = await self._connector.place_order(
                    symbol=order.symbol,
                    side=order.action.value,
                    order_type="limit" if order.limit_price else "market",
                    quantity=order.quantity,
                    price=order.limit_price,
                )
                results.append({
                    "order": order,
                    "exchange_order": exchange_order,
                    "status": "submitted",
                    "success": True,
                })
                logger.info("SUBMITTED: %s %s → order_id=%s", order.symbol, order.action.value,
                            getattr(exchange_order, "order_id", "?"))
            except Exception as e:
                logger.error("FAILED: %s %s — %s", order.symbol, order.action.value, e)
                results.append({"order": order, "status": "error", "success": False, "error": str(e)})

        return results

    # ── Summary ─────────────────────────────────────────────────────────

    def get_summary(self) -> Dict[str, Any]:
        return {
            "executor": "WarRoomExecutor",
            "dry_run": self.dry_run,
            "connected": self._connected,
            "ibkr_available": IBKR_AVAILABLE,
            "war_room_available": WAR_ROOM_AVAILABLE,
            "doctrine_available": DOCTRINE_AVAILABLE,
            "max_premium_per_order": self.max_premium_per_order,
            "max_total_premium": self.max_total_premium,
        }


# ── Singleton ───────────────────────────────────────────────────────────

_executor: Optional[WarRoomExecutor] = None


def get_war_room_executor(**kwargs: Any) -> WarRoomExecutor:
    global _executor
    if _executor is None:
        _executor = WarRoomExecutor(**kwargs)
    return _executor
